### ISSUE TITLE
How to use multi servers ?

### ISSUE THREAD

**Issue by sallsabil** [clue/reactphp-socks#76]
`$proxy = new Client('socks5://' . rawurlencode(PROXY_USER) . ':' . rawurlencode(PROXY_PASS) . '@' . PROXY_ADDRESS . ':' . PROXY_PORT, new React\Socket\Connector($loop));`

I need to use multi PROXY_ADDRESS servers when one is slow or stopped another server process.
Is there any Solution ?

**Comment by clue** [comment]
@sallsabil Thanks your your excellent question!

You can simply create multiple SOCKS connectors (one for each server instance) and then need to wrap this in an instance that implements your particular strategy to pick the "right" one. For example, take a look at https://github.com/clue/reactphp-socks/blob/master/examples/22-server-proxy-chaining-from-random-pool.php#L36 which uses a pool of proxy servers and always picks a random one for each connection attempt.

Let me know how this works for your use case, perhaps we can eventually provide a better way to automatically pick the "right" server.

I hope this helps! 👍

**Comment by sallsabil** [comment]
It is a better solution than the basic one
But as I'm using it for Telegram bot I'm going to see if there is a better solution to speed up the process.
So this is my code:
```
$loop = Factory::create();
$proxy = new Client('socks5://' . rawurlencode(PROXY_USER) . ':' . rawurlencode(PROXY_PASS) . '@' . PROXY_ADDRESS . ':' . PROXY_PORT, new React\Socket\Connector($loop));
$handler = new HttpClientRequestHandler($loop, [
    'tcp' => $proxy,
    'timeout' => 3.0,
    'dns' => false
]);
$tgLog = new TgLog(BOT_TOKEN, $handler);
```
How can I let the code use another server if the 3 second timed out ?

**Comment by clue** [comment]
You can build a SOCKS connector for both of your servers and then use https://github.com/clue/reactphp-connection-manager-extra#consecutive to always try the first followed by the second one.
