### ISSUE TITLE
How to use MTProto ?

### ISSUE THREAD

**Issue by sallsabil** [clue/reactphp-socks#77]
Telegram has a special proxy type named MTProto (Instead of Username and Password it has Credentials(Secret)).
How to use it ?

**Comment by clue** [comment]
This project implements the SOCKS proxy protocol family. The SOCKS protocol can be used to tunnel any TCP/IP-based protocol, such as HTTP(S), IMAP(S), SMTP(S) etc.

Telegram supports a number of different proxy setups, including SOCKS5. This means that you should be able to use Telegram with this project just fine.

Additionally, Telegram supports "MTProto proxy", a protocol specifically designed for Telegram's protocol ("MTProto"). Given that it has little to do with SOCKS, it's my understanding that this is out of scope for this library.

I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can reopen this :+1:
